---
uint16 NONE = 0
uint16 SAFE_START = 1
uint16 CHANNEL_INVALID = 2
uint16 SERIAL = 4
uint16 COMMAND_TIMEOUT = 8
uint16 LIMIT_SWITCH = 16
uint16 VIN_LOW = 32
uint16 VIN_HIGH = 64
uint16 TEMPERATURE_HIGH = 128
uint16 MOTOR_DRIVER = 256
uint16 LINE_HIGH = 512

uint16 errors
