---
uint16 NONE = 0
uint16 SERIAL_SIGN = 1
uint16 SERIAL_OVERRUN = 2
uint16 SERIAL_BUFFER_FULL = 4
uint16 SERIAL_CRC = 8
uint16 SERIAL_PROTOCOL = 16
uint16 SERIAL_TIMEOUT = 32
uint16 SCRIPT_STACK = 64
uint16 SCRIPT_CALL_STACK = 128
uint16 SCRIPT_PROGRAM_COUNTER = 256

uint16 errors # OR'ed flags as given above
