position:
    name: "TankPositionFront"
    hallSensorName: "hallSensor_front"
    hallSensorReadingFreq: 100.0
    totalTicks: 950
control:
    name: "TankCtrlFront"
    smcServer: "smc_server_front"
    checkPosFreq: 100.0
positionThreshold: 0.05
