position:
    name: "TankPositionRear"
    hallSensorName: "hallSensor_rear"
    hallSensorReadingFreq: 100.0
    totalTicks: 950
control:
    name: "TankCtrlRear"
    smcServer: "smc_server_rear"
    checkPosFreq: 100.0
positionThreshold: 0.01
