server:
  smc:
    name: smc_server
  sensor:
    name: depth_sensor
  connection:
    retry: 0.1
model:
  gravitational_acceleration: 9.80665
  fluid:
    density: 1000.0
  platform:
    mass: 10.0
    area: 0.1
    volume: 0.012
    drag_coefficient: 1.0
  actuator:
    max_flow_rate: 20e-6
actuator:
  limits:
    minimum:
      input_channel: 128
    maximum:
      input_channel: 256
  inverted: true
controller:
  frequency: 5.0
  tolerance:
    depth: 0.1
    velocity: 0.0
  gain:
    proportional: 1e-2
    integral: 1e-1
    differential: 0.0
