Depth:
    Frequency: 100
    Kp: 1.0
    Ki: 0.0
    Kd: 0.0
    InitialInput: 0.4
Pitch:
    Frequency: 150
    Kp: 1.0
    Ki: 0.0
    Kd: 0.0
    InitialInput: 0.0
Services:
    tankFrontCtrl: "TankCtrlFront"
    tankRearCtrl: "TankCtrlRear"
    depthService: "DepthSensor"
    pitchService: "naro_imu_node"
Tank:
    Speed: 0.6