Depth:
    Frequency: 100
    Kp: 0.1155
    Ki: 0.0062
    Kd: 1.4245
Pitch:
    Frequency: 1
    Kp: 0.2
    Ki: 0.0
    Kd: 0.0
Services:
    tankFrontCtrl: "TankCtrlFront"
    tankRearCtrl: "TankCtrlRear"
    depthService: "DepthSensor"
    pitchService: "naro_imu_node"
Tank:
    Speed: 0.6