Depth:
    Frequency: 100
    Kp: 2.1
    Ki: 0.2471
    Kd: 4.4625
    InitialInput: 0.0
Pitch:
    Frequency: 150
    Kp: 0.72
    Ki: 0.24
    Kd: 0.52
    InitialInput: 0.0
Services:
    tankFrontCtrl: "TankCtrlFront"
    tankRearCtrl: "TankCtrlRear"
    depthService: "DepthSensor"
    pitchService: "naro_imu_node"
Tank:
    Speed: 0.7
