byte fin
byte actuator # values as given in Actuator.msg
byte input_channel
byte output_channel # values as given in OutputChannel.msg
byte transfer_function # values as given in Coefficient.msg
bool invert_arguments
bool invert_values
---
