fins:
  ventral_left:
    pitch:
      servo: 0
      frequency:
        constant: 2.0
      amplitude:
        constant: 25.0
        coefficients:
          ventral_left_flap:
            input_channel: 1
          ventral_left_gain:
            input_channel: 3
            transfer_function: slope
      phase:
        constant: 90.0
    flap:
      servo: 1
      frequency:
        constant: 2.0
      amplitude:
        constant: 20.0
        coefficients:
          ventral_left_flap:
            input_channel: 1
          ventral_left_gain:
            input_channel: 3
            transfer_function: slope
  ventral_right:
    pitch:
      servo: 2
      frequency:
        constant: 2.0
      amplitude:
        constant: 25.0
        coefficients:
          ventral_right_flap:
            input_channel: 1
            invert_arguments: true
          ventral_right_gain:
            input_channel: 3
            transfer_function: slope
            invert_arguments: true
      phase:
        constant: 90.0
    flap:
      servo: 3
      frequency:
        constant: 2.0
      amplitude:
        constant: 20.0
        coefficients:
          ventral_right_flap:
            input_channel: 1
            invert_arguments: true
          ventral_right_gain:
            input_channel: 3
            transfer_function: slope
            invert_arguments: true
  dorsal:
    flap:
      servo: 5
      offset:
        constant: 20.0
        coefficients:
          dorsal_pitch:
            input_channel: 3
  tail:
    pitch:
      servo: 6
      frequency:
        constant: 2.0
      amplitude:
        constant: 20.0
        coefficients:
          tail_pitch:
            input_channel: 1
      offset:
        constant: 30.0
        coefficients:
          tail_pitch:
            input_channel: 3
 